export enum ApiType {
  Addresses = 'addresses',
  Attachments = 'attachments',
  BusinessPartners = 'businesspartners',
  Companies = 'companies',
  Dashboard = 'dashboard',
  Individuals = 'individuals',
  Orders = 'orders',
  OrderProducts = 'orderproducts',
  Quotes = 'quotes',
  QuoteProducts = 'quoteproducts',
  Transactions = 'transactions',
  Payments = 'payments',
  Photos = 'photos',
  Products = 'products',
  Users = 'users',
  Vehicles = 'vehicles',
  VehicleMaintenances = 'vehiclemaintenances',
  Drivers = 'drivers',
}
