using AutoMapper;
using TSI.Friday.Contracts.Enums;
using TSI.Friday.Contracts.Models;
using TSI.Friday.Contracts.Models.DTOs;

namespace TSI.Friday.IoC
{
    public class MappingProfile : Profile
    {
        public MappingProfile()
        {
            // Address mappings
            CreateMap<Address, AddressDto>();
            CreateMap<AddressDto, Address>()
                .ForAllMembers(opts => opts.Condition((src, dest, srcMember) => srcMember != null));

            // BusinessPartner mappings
            // Map DTO directly to concrete types first
            CreateMap<BusinessPartnerDto, Individual>()
                .ForAllMembers(opts => opts.Condition((src, dest, srcMember) => srcMember != null));
            CreateMap<BusinessPartnerDto, Company>()
                .ForAllMembers(opts => opts.Condition((src, dest, srcMember) => srcMember != null));

            // Map BusinessPartner -> BusinessPartnerDto (reading from DB)
            CreateMap<BusinessPartner, BusinessPartnerDto>()
                .ForMember(
                    dest => dest.SocialSecurityCard,
                    opt =>
                        opt.MapFrom(src =>
                            (src as Individual) != null
                                ? ((Individual)src).SocialSecurityCard
                                : null
                        )
                )
                .ForMember(
                    dest => dest.NationalIdCard,
                    opt =>
                        opt.MapFrom(src =>
                            (src as Individual) != null ? ((Individual)src).NationalIdCard : default
                        )
                )
                .ForMember(
                    dest => dest.Birthday,
                    opt =>
                        opt.MapFrom(src =>
                            (src as Individual) != null ? ((Individual)src).Birthday : default
                        )
                )
                .ForMember(
                    dest => dest.NationalRegistry,
                    opt =>
                        opt.MapFrom(src =>
                            (src as Company) != null ? ((Company)src).NationalRegistry : null
                        )
                )
                .ForMember(
                    dest => dest.NextEmptyTransactionId,
                    opt =>
                        opt.MapFrom(src =>
                            src.Transactions != null
                                ? src
                                    .Transactions.Where(t => t.OrderId == null)
                                    .OrderBy(t => t.Date)
                                    .Select(t => (Guid?)t.Id)
                                    .FirstOrDefault()
                                : null
                        )
                );

            // Construct BusinessPartner (base) from DTO by dispatching to concrete maps
            CreateMap<BusinessPartnerDto, BusinessPartner>()
                .ConstructUsing(
                    (src, ctx) =>
                    {
                        var type = (src?.DocumentType ?? string.Empty).Trim().ToLowerInvariant();

                        return type switch
                        {
                            "física" or "fisica" => ctx.Mapper.Map<Individual>(src),
                            "jurídica" or "juridica" => ctx.Mapper.Map<Company>(src),
                            // Default to Individual when Type is missing or unrecognized to avoid throwing during config validation
                            _ => ctx.Mapper.Map<Individual>(src),
                        };
                    }
                )
                // keep null-value filtering for member updates if needed
                .ForAllMembers(opts => opts.Condition((src, dest, srcMember) => srcMember != null));

            // User mappings
            CreateMap<UserDto, User>()
                .ForMember(dest => dest.Role, opt => opt.MapFrom(src => src.Role))
                .ForAllMembers(opts => opts.Condition((src, dest, srcMember) => srcMember != null));

            CreateMap<User, UserDto>()
                .ForMember(dest => dest.Role, opt => opt.MapFrom(src => src.Role))
                // JWT is generated by services, avoid mapping here to not overwrite
                .ForMember(dest => dest.JWT, opt => opt.Ignore());

            // Order mappings
            CreateMap<Order, OrderDto>()
                .ForMember(dest => dest.TotalPrice, opt => opt.MapFrom(src => src.TotalPrice))
                .ForMember(
                    dest => dest.BusinessPartnerName,
                    opt =>
                        opt.MapFrom(src =>
                            src.BusinessPartner != null ? src.BusinessPartner.Name : null
                        )
                )
                .ForMember(dest => dest.Transaction, opt => opt.MapFrom(src => src.Transaction))
                // also map nested flags directly from entity Transaction.Payments when possible
                .ForPath(
                    dest => dest.Transaction.HasOpenedPayments,
                    opt =>
                        opt.MapFrom(src =>
                            src.Transaction != null
                            && src.Transaction.Payments != null
                            && src.Transaction.Payments.Any(p => p.Status != PaymentStatus.Approved)
                        )
                )
                .ForPath(
                    dest => dest.Transaction.MarkAllPaymentsAsApproved,
                    opt =>
                        opt.MapFrom(src =>
                            src.Transaction != null
                            && src.Transaction.Payments != null
                            && src.Transaction.Payments.Any()
                            && src.Transaction.Payments.All(p => p.Status == PaymentStatus.Approved)
                        )
                )
                .AfterMap(
                    (src, dest) =>
                    {
                        // compute TransactionDto.Status and other flags from mapped PaymentDto statuses when mapping entity -> dto
                        if (dest?.Transaction != null)
                        {
                            var payments =
                                dest.Transaction.Payments?.ToList() ?? new List<PaymentDto>();
                            if (payments.Any())
                            {
                                if (payments.Any(p => p.Status == PaymentStatus.Delayed))
                                {
                                    dest.Transaction.Status = PaymentStatus.Delayed;
                                }
                                else if (payments.Any(p => p.Status == PaymentStatus.Pending))
                                {
                                    dest.Transaction.Status = PaymentStatus.Pending;
                                }
                                else if (payments.All(p => p.Status == PaymentStatus.Approved))
                                {
                                    dest.Transaction.Status = PaymentStatus.Approved;
                                }

                                // HasOpenedPayments: true when there is any payment not approved
                                dest.Transaction.HasOpenedPayments = payments.Any(p =>
                                    p.Status != PaymentStatus.Approved
                                );

                                // MarkAllPaymentsAsApproved: true when there are payments and all are approved
                                dest.Transaction.MarkAllPaymentsAsApproved =
                                    payments.Any()
                                    && payments.All(p => p.Status == PaymentStatus.Approved);
                            }
                            else
                            {
                                dest.Transaction.HasOpenedPayments = false;
                                dest.Transaction.MarkAllPaymentsAsApproved = false;
                            }
                        }
                    }
                );

            var orderDtoToOrderMap = CreateMap<OrderDto, Order>();
            orderDtoToOrderMap.ForMember(
                dest => dest.Transaction,
                opt => opt.MapFrom(src => src.Transaction)
            );
            orderDtoToOrderMap.ForAllMembers(opts =>
                opts.Condition((src, dest, srcMember) => srcMember != null)
            );
            // removed AfterMap here because transaction status should be computed when mapping to DTO (entity -> dto)

            // PurchaseOrder mappings
            CreateMap<PurchaseOrder, PurchaseOrderDto>()
                .ForMember(dest => dest.TotalPrice, opt => opt.MapFrom(src => src.TotalPrice))
                .ForMember(
                    dest => dest.BusinessPartnerName,
                    opt =>
                        opt.MapFrom(src =>
                            src.BusinessPartner != null ? src.BusinessPartner.Name : null
                        )
                )
                .ForMember(dest => dest.Transaction, opt => opt.MapFrom(src => src.Transaction))
                .ForPath(
                    dest => dest.Transaction.HasOpenedPayments,
                    opt =>
                        opt.MapFrom(src =>
                            src.Transaction != null
                            && src.Transaction.Payments != null
                            && src.Transaction.Payments.Any(p => p.Status != PaymentStatus.Approved)
                        )
                )
                .ForPath(
                    dest => dest.Transaction.MarkAllPaymentsAsApproved,
                    opt =>
                        opt.MapFrom(src =>
                            src.Transaction != null
                            && src.Transaction.Payments != null
                            && src.Transaction.Payments.Any()
                            && src.Transaction.Payments.All(p => p.Status == PaymentStatus.Approved)
                        )
                )
                .AfterMap(
                    (src, dest) =>
                    {
                        if (dest?.Transaction != null)
                        {
                            var payments =
                                dest.Transaction.Payments?.ToList() ?? new List<PaymentDto>();
                            if (payments.Any())
                            {
                                if (payments.Any(p => p.Status == PaymentStatus.Delayed))
                                {
                                    dest.Transaction.Status = PaymentStatus.Delayed;
                                }
                                else if (payments.Any(p => p.Status == PaymentStatus.Pending))
                                {
                                    dest.Transaction.Status = PaymentStatus.Pending;
                                }
                                else if (payments.All(p => p.Status == PaymentStatus.Approved))
                                {
                                    dest.Transaction.Status = PaymentStatus.Approved;
                                }

                                dest.Transaction.HasOpenedPayments = payments.Any(p =>
                                    p.Status != PaymentStatus.Approved
                                );

                                dest.Transaction.MarkAllPaymentsAsApproved =
                                    payments.Any()
                                    && payments.All(p => p.Status == PaymentStatus.Approved);
                            }
                            else
                            {
                                dest.Transaction.HasOpenedPayments = false;
                                dest.Transaction.MarkAllPaymentsAsApproved = false;
                            }
                        }
                    }
                );

            var purchaseOrderDtoToPurchaseOrderMap = CreateMap<PurchaseOrderDto, PurchaseOrder>();
            purchaseOrderDtoToPurchaseOrderMap.ForMember(
                dest => dest.Transaction,
                opt => opt.MapFrom(src => src.Transaction)
            );
            purchaseOrderDtoToPurchaseOrderMap.ForAllMembers(opts =>
                opts.Condition((src, dest, srcMember) => srcMember != null)
            );

            // PurchaseOrderProduct mappings
            CreateMap<PurchaseOrderProduct, PurchaseOrderProductDto>()
                .ForMember(dest => dest.TotalPrice, opt => opt.MapFrom(src => src.TotalPrice))
                .ForMember(
                    dest => dest.PurchaseOrderNumber,
                    opt =>
                        opt.MapFrom(src =>
                            src.PurchaseOrder != null ? src.PurchaseOrder.PurchaseOrderNumber : null
                        )
                )
                .ForMember(
                    dest => dest.ProductSku,
                    opt => opt.MapFrom(src => src.Product != null ? src.Product.Sku : null)
                )
                .ForMember(
                    dest => dest.ProductName,
                    opt => opt.MapFrom(src => src.Product != null ? src.Product.Name : null)
                )
                .ForMember(
                    dest => dest.ProductType,
                    opt =>
                        opt.MapFrom(src =>
                            src.Product != null ? src.Product.Type : ProductType.Sale
                        )
                )
                .ForMember(
                    dest => dest.BusinessPartnerId,
                    opt =>
                        opt.MapFrom(src =>
                            src.PurchaseOrder != null
                                ? src.PurchaseOrder.BusinessPartnerId
                                : Guid.Empty
                        )
                )
                .ForMember(
                    dest => dest.BusinessPartnerName,
                    opt =>
                        opt.MapFrom(src =>
                            src.PurchaseOrder != null && src.PurchaseOrder.BusinessPartner != null
                                ? src.PurchaseOrder.BusinessPartner.Name
                                : null
                        )
                )
                .ForMember(dest => dest.PreviousQuantity, opt => opt.MapFrom(src => src.Quantity));

            CreateMap<PurchaseOrderProductDto, PurchaseOrderProduct>()
                .ForAllMembers(opts => opts.Condition((src, dest, srcMember) => srcMember != null));

            // VehicleMaintenanceProduct mappings
            CreateMap<VehicleMaintenanceProduct, VehicleMaintenanceProductDto>()
                .ForMember(dest => dest.TotalPrice, opt => opt.MapFrom(src => src.TotalPrice))
                .ForMember(
                    dest => dest.VehicleId,
                    opt =>
                        opt.MapFrom(src =>
                            src.VehicleMaintenance != null
                                ? src.VehicleMaintenance.VehicleId
                                : Guid.Empty
                        )
                )
                .ForMember(
                    dest => dest.VehiclePlate,
                    opt =>
                        opt.MapFrom(src =>
                            src.VehicleMaintenance != null && src.VehicleMaintenance.Vehicle != null
                                ? src.VehicleMaintenance.Vehicle.Plate
                                : null
                        )
                )
                .ForMember(
                    dest => dest.ProductSku,
                    opt => opt.MapFrom(src => src.Product != null ? src.Product.Sku : null)
                )
                .ForMember(
                    dest => dest.ProductName,
                    opt => opt.MapFrom(src => src.Product != null ? src.Product.Name : null)
                )
                .ForMember(
                    dest => dest.ProductType,
                    opt =>
                        opt.MapFrom(src =>
                            src.Product != null ? src.Product.Type : ProductType.Sale
                        )
                )
                .ForMember(dest => dest.PreviousQuantity, opt => opt.MapFrom(src => src.Quantity));

            CreateMap<VehicleMaintenanceProductDto, VehicleMaintenanceProduct>()
                .ForAllMembers(opts => opts.Condition((src, dest, srcMember) => srcMember != null));

            // Trip mappings
            CreateMap<Trip, TripDto>()
                .ForMember(dest => dest.TotalPrice, opt => opt.MapFrom(src => src.TotalPrice))
                .ForMember(
                    dest => dest.BusinessPartnerName,
                    opt =>
                        opt.MapFrom(src =>
                            src.BusinessPartner != null ? src.BusinessPartner.Name : null
                        )
                )
                .ForMember(
                    dest => dest.VehiclePlate,
                    opt => opt.MapFrom(src => src.Vehicle != null ? src.Vehicle.Plate : null)
                )
                .ForMember(
                    dest => dest.DriverName,
                    opt => opt.MapFrom(src => src.Driver != null ? src.Driver.Name : null)
                )
                .ForMember(dest => dest.Transaction, opt => opt.MapFrom(src => src.Transaction))
                // also map nested flags directly from entity Transaction.Payments when possible
                .ForPath(
                    dest => dest.Transaction.HasOpenedPayments,
                    opt =>
                        opt.MapFrom(src =>
                            src.Transaction != null
                            && src.Transaction.Payments != null
                            && src.Transaction.Payments.Any(p => p.Status != PaymentStatus.Approved)
                        )
                )
                .ForPath(
                    dest => dest.Transaction.MarkAllPaymentsAsApproved,
                    opt =>
                        opt.MapFrom(src =>
                            src.Transaction != null
                            && src.Transaction.Payments != null
                            && src.Transaction.Payments.Any()
                            && src.Transaction.Payments.All(p => p.Status == PaymentStatus.Approved)
                        )
                )
                .AfterMap(
                    (src, dest) =>
                    {
                        // compute TransactionDto.Status and other flags from mapped PaymentDto statuses when mapping entity -> dto
                        if (dest?.Transaction != null)
                        {
                            var payments =
                                dest.Transaction.Payments?.ToList() ?? new List<PaymentDto>();
                            if (payments.Any())
                            {
                                if (payments.Any(p => p.Status == PaymentStatus.Delayed))
                                {
                                    dest.Transaction.Status = PaymentStatus.Delayed;
                                }
                                else if (payments.Any(p => p.Status == PaymentStatus.Pending))
                                {
                                    dest.Transaction.Status = PaymentStatus.Pending;
                                }
                                else if (payments.All(p => p.Status == PaymentStatus.Approved))
                                {
                                    dest.Transaction.Status = PaymentStatus.Approved;
                                }

                                dest.Transaction.HasOpenedPayments = payments.Any(p =>
                                    p.Status != PaymentStatus.Approved
                                );

                                dest.Transaction.MarkAllPaymentsAsApproved =
                                    payments.Any()
                                    && payments.All(p => p.Status == PaymentStatus.Approved);
                            }
                            else
                            {
                                dest.Transaction.HasOpenedPayments = false;
                                dest.Transaction.MarkAllPaymentsAsApproved = false;
                            }
                        }
                    }
                );

            var tripDtoToTripMap = CreateMap<TripDto, Trip>();
            tripDtoToTripMap.ForMember(
                dest => dest.Transaction,
                opt => opt.MapFrom(src => src.Transaction)
            );
            tripDtoToTripMap.ForAllMembers(opts =>
                opts.Condition((src, dest, srcMember) => srcMember != null)
            );

            // OrderProduct mappings
            CreateMap<OrderProduct, OrderProductDto>()
                .ForMember(dest => dest.TotalPrice, opt => opt.MapFrom(src => src.TotalPrice))
                .ForMember(
                    dest => dest.OrderNumber,
                    opt => opt.MapFrom(src => src.Order != null ? src.Order.OrderNumber : null)
                )
                .ForMember(
                    dest => dest.ProductSku,
                    opt => opt.MapFrom(src => src.Product != null ? src.Product.Sku : null)
                )
                .ForMember(
                    dest => dest.ProductName,
                    opt => opt.MapFrom(src => src.Product != null ? src.Product.Name : null)
                )
                .ForMember(
                    dest => dest.ProductType,
                    opt =>
                        opt.MapFrom(src =>
                            src.Product != null ? src.Product.Type : ProductType.Sale
                        )
                )
                .ForMember(
                    dest => dest.BusinessPartnerId,
                    opt =>
                        opt.MapFrom(src =>
                            src.Order != null ? src.Order.BusinessPartnerId : Guid.Empty
                        )
                )
                .ForMember(
                    dest => dest.BusinessPartnerName,
                    opt =>
                        opt.MapFrom(src =>
                            src.Order != null && src.Order.BusinessPartner != null
                                ? src.Order.BusinessPartner.Name
                                : null
                        )
                )
                .ForMember(dest => dest.PreviousQuantity, opt => opt.MapFrom(src => src.Quantity));

            CreateMap<OrderProductDto, OrderProduct>()
                .ForAllMembers(opts => opts.Condition((src, dest, srcMember) => srcMember != null));

            // TripDriver mappings
            CreateMap<TripDriver, TripDriverDto>()
                .ForMember(
                    dest => dest.TripNumber,
                    opt => opt.MapFrom(src => src.Trip != null ? src.Trip.TripNumber : null)
                )
                .ForMember(
                    dest => dest.DriverName,
                    opt => opt.MapFrom(src => src.Driver != null ? src.Driver.Name : null)
                )
                .ForMember(
                    dest => dest.DriverLicenseNumber,
                    opt =>
                        opt.MapFrom(src => src.Driver != null ? src.Driver.LicenseNumber : null)
                )
                .ForMember(
                    dest => dest.DriverLicenseExpiryDate,
                    opt =>
                        opt.MapFrom(src =>
                            src.Driver != null ? src.Driver.LicenseExpiryDate : default
                        )
                );

            CreateMap<TripDriverDto, TripDriver>()
                .ForAllMembers(opts => opts.Condition((src, dest, srcMember) => srcMember != null));

            // Transaction mappings
            CreateMap<Transaction, TransactionDto>()
                .ForMember(
                    dest => dest.OrderNumber,
                    opt => opt.MapFrom(src => src.Order != null ? src.Order.OrderNumber : null)
                )
                .ForMember(
                    dest => dest.TripNumber,
                    opt => opt.MapFrom(src => src.Trip != null ? src.Trip.TripNumber : null)
                )
                .ForMember(
                    dest => dest.BusinessPartnerName,
                    opt =>
                        opt.MapFrom(src =>
                            src.BusinessPartner != null ? src.BusinessPartner.Name : null
                        )
                )
                // Transaction -> TransactionDto mapping: compute totals from Payments
                .ForMember(
                    dest => dest.TotalOfPayments,
                    opt =>
                        opt.MapFrom(src =>
                            src.Payments == null
                                ? 0
                                : src.Payments.Count(_ => PaymentType.Incoming.Equals(_.Type))
                        )
                )
                // Transaction -> TransactionDto mapping: compute totals from Payments
                .ForMember(
                    dest => dest.TotalOfExpenses,
                    opt =>
                        opt.MapFrom(src =>
                            src.Payments == null
                                ? 0
                                : src.Payments.Count(_ => PaymentType.Outgoing.Equals(_.Type))
                        )
                )
                .ForMember(
                    dest => dest.PaymentTotalPrice,
                    opt =>
                        opt.MapFrom(src =>
                            src.Payments == null
                                ? 0m
                                : src.Payments.Sum(p =>
                                    PaymentType.Incoming.Equals(p.Type) ? p.Price : 0m
                                )
                        )
                )
                .ForMember(
                    dest => dest.ExpenseTotalPrice,
                    opt =>
                        opt.MapFrom(src =>
                            src.Payments == null
                                ? 0m
                                : src.Payments.Sum(p =>
                                    PaymentType.Outgoing.Equals(p.Type) ? p.Price : 0m
                                )
                        )
                )
                // Map Payments collection to DTO
                .ForMember(dest => dest.Payments, opt => opt.MapFrom(src => src.Payments))
                // HasOpenedPayments: true when there is any payment not approved (kept for safety, will be recomputed in Order mapping)
                .ForMember(
                    dest => dest.HasOpenedPayments,
                    opt =>
                        opt.MapFrom(src =>
                            src.Payments != null
                            && src.Payments.Any(p => p.Status != PaymentStatus.Approved)
                        )
                );

            CreateMap<TransactionDto, Transaction>()
                // TransactionDto -> Transaction: ignore read-only computed members
                .ForMember(dest => dest.Payments, opt => opt.Ignore())
                .ForMember(
                    dest => dest.Id,
                    opt => opt.Condition((src, dest, srcMember) => srcMember != Guid.Empty)
                )
                .ForAllMembers(opts => opts.Condition((src, dest, srcMember) => srcMember != null));

            // Payment mappings
            CreateMap<Payment, PaymentDto>()
                .ForMember(
                    dest => dest.OrderNumber,
                    opt => opt.MapFrom(src => src.Order != null ? src.Order.OrderNumber : null)
                )
                .ForMember(
                    dest => dest.TripNumber,
                    opt => opt.MapFrom(src => src.Trip != null ? src.Trip.TripNumber : null)
                )
                .ForMember(
                    dest => dest.BusinessPartnerName,
                    opt =>
                        opt.MapFrom(src =>
                            src.BusinessPartner != null ? src.BusinessPartner.Name : null
                        )
                )
                .ForMember(
                    dest => dest.BusinessPartnerType,
                    opt =>
                        opt.MapFrom(src =>
                            src.BusinessPartner != null
                                ? (BusinessPartnerType?)src.BusinessPartner.Type
                                : null
                        )
                )
                .ForMember(
                    dest => dest.TransactionDescription,
                    opt =>
                        opt.MapFrom(src =>
                            src.Transaction != null ? src.Transaction.Description : null
                        )
                )
                .ForMember(
                    dest => dest.DriverName,
                    opt => opt.MapFrom(src => src.Driver != null ? src.Driver.Name : null)
                );
            CreateMap<PaymentDto, Payment>()
                .ForAllMembers(opts => opts.Condition((src, dest, srcMember) => srcMember != null));

            // Quote mappings
            CreateMap<Quote, QuoteDto>()
                .ForMember(dest => dest.TotalPrice, opt => opt.MapFrom(src => src.TotalPrice))
                .ForMember(
                    dest => dest.BusinessPartnerName,
                    opt =>
                        opt.MapFrom(src =>
                            src.BusinessPartner != null ? src.BusinessPartner.Name : null
                        )
                )
                // map entity QuoteNumber -> dto OrderNumber
                .ForMember(dest => dest.QuoteNumber, opt => opt.MapFrom(src => src.QuoteNumber))
                .ForMember(
                    dest => dest.QuoteProducts,
                    opt => opt.MapFrom(src => src.QuoteProducts)
                )
                .ForMember(dest => dest.QuoteTrip, opt => opt.MapFrom(src => src.QuoteTrip));

            CreateMap<QuoteDto, Quote>()
                // map dto OrderNumber -> entity QuoteNumber
                .ForMember(dest => dest.QuoteNumber, opt => opt.MapFrom(src => src.QuoteNumber))
                .ForMember(dest => dest.QuoteTrip, opt => opt.Ignore())
                .ForAllMembers(opts => opts.Condition((src, dest, srcMember) => srcMember != null));

            // QuoteTrip mappings
            CreateMap<QuoteTrip, QuoteTripDto>()
                .ForMember(
                    dest => dest.VehiclePlate,
                    opt => opt.MapFrom(src => src.Vehicle != null ? src.Vehicle.Plate : null)
                )
                .ForMember(
                    dest => dest.DriverName,
                    opt => opt.MapFrom(src => src.Driver != null ? src.Driver.Name : null)
                );

            CreateMap<QuoteTripDto, QuoteTrip>()
                .ForAllMembers(opts => opts.Condition((src, dest, srcMember) => srcMember != null));

            // QuoteProduct mappings
            CreateMap<QuoteProduct, QuoteProductDto>()
                .ForMember(dest => dest.TotalPrice, opt => opt.MapFrom(src => src.TotalPrice))
                .ForMember(dest => dest.OrderId, opt => opt.MapFrom(src => src.QuoteId))
                .ForMember(
                    dest => dest.OrderNumber,
                    opt => opt.MapFrom(src => src.Quote != null ? src.Quote.QuoteNumber : null)
                )
                .ForMember(
                    dest => dest.ProductSku,
                    opt => opt.MapFrom(src => src.Product != null ? src.Product.Sku : null)
                )
                .ForMember(
                    dest => dest.ProductName,
                    opt => opt.MapFrom(src => src.Product != null ? src.Product.Name : null)
                )
                .ForMember(
                    dest => dest.ProductType,
                    opt =>
                        opt.MapFrom(src =>
                            src.Product != null ? src.Product.Type : ProductType.Sale
                        )
                )
                .ForMember(
                    dest => dest.BusinessPartnerId,
                    opt =>
                        opt.MapFrom(src =>
                            src.Quote != null ? src.Quote.BusinessPartnerId : Guid.Empty
                        )
                )
                .ForMember(
                    dest => dest.BusinessPartnerName,
                    opt =>
                        opt.MapFrom(src =>
                            src.Quote != null && src.Quote.BusinessPartner != null
                                ? src.Quote.BusinessPartner.Name
                                : null
                        )
                )
                .ForMember(dest => dest.PreviousQuantity, opt => opt.MapFrom(src => src.Quantity));

            CreateMap<QuoteProductDto, QuoteProduct>()
                .ForMember(dest => dest.QuoteId, opt => opt.MapFrom(src => src.OrderId))
                .ForAllMembers(opts => opts.Condition((src, dest, srcMember) => srcMember != null));

            // Event mappings
            CreateMap<Event, EventDto>()
                .ForMember(
                    dest => dest.EventTypeName,
                    opt => opt.MapFrom(src => src.EventType != null ? src.EventType.Value : null)
                )
                .ForMember(
                    dest => dest.EventTypeColor,
                    opt => opt.MapFrom(src => src.EventType != null ? src.EventType.Color : null)
                )
                .ForMember(
                    dest => dest.CreatedByUserName,
                    opt =>
                        opt.MapFrom(src =>
                            src.CreatedByUser != null
                                ? (src.CreatedByUser.FirstName + " " + src.CreatedByUser.LastName).Trim()
                                : null
                        )
                )
                .ForMember(
                    dest => dest.LinkedEntityType,
                    opt =>
                        opt.MapFrom(src =>
                            src.BusinessPartner != null ? "BusinessPartner"
                            : src.Order != null ? "Order"
                            : src.PurchaseOrder != null ? "PurchaseOrder"
                            : src.Quote != null ? "Quote"
                            : src.Trip != null ? "Trip"
                            : src.Transaction != null ? "Transaction"
                            : src.Payment != null ? "Payment"
                            : src.Vehicle != null ? "Vehicle"
                            : src.Driver != null ? "Driver"
                            : src.VehicleMaintenance != null ? "VehicleMaintenance"
                            : src.FuelLog != null ? "FuelLog"
                            : null
                        )
                )
                .ForMember(
                    dest => dest.LinkedEntityLabel,
                    opt =>
                        opt.MapFrom(src =>
                            src.BusinessPartner != null ? src.BusinessPartner.Name
                            : src.Order != null ? src.Order.OrderNumber
                            : src.PurchaseOrder != null ? src.PurchaseOrder.PurchaseOrderNumber
                            : src.Quote != null ? src.Quote.QuoteNumber
                            : src.Trip != null ? src.Trip.TripNumber
                            : src.Transaction != null ? src.Transaction.Description
                            : src.Payment != null ? src.Payment.Description
                            : src.Vehicle != null ? src.Vehicle.Plate
                            : src.Driver != null ? src.Driver.Name
                            : src.VehicleMaintenance != null ? src.VehicleMaintenance.Description
                            : src.FuelLog != null ? src.FuelLog.GasStation
                            : null
                        )
                );

            CreateMap<EventDto, Event>()
                .ForMember(dest => dest.Participants, opt => opt.Ignore())
                .ForAllMembers(opts => opts.Condition((src, dest, srcMember) => srcMember != null));

            // EventParticipant mappings
            CreateMap<EventParticipant, EventParticipantDto>()
                .ForMember(
                    dest => dest.DisplayName,
                    opt =>
                        opt.MapFrom(src =>
                            src.UserId != null ? null : (src.Name ?? src.Email)
                        )
                );

            CreateMap<EventParticipantDto, EventParticipant>()
                .ForAllMembers(opts => opts.Condition((src, dest, srcMember) => srcMember != null));
        }
    }
}
