<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.1" />
    <PackageReference
      Include="AutoMapper.Extensions.Microsoft.DependencyInjection"
      Version="12.0.1"
    />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\TSI.Friday.Contracts\src\TSI.Friday.Contracts\TSI.Friday.Contracts.csproj" />
    <ProjectReference Include="..\..\..\TSI.Friday.Repository\src\TSI.Friday.Repository\TSI.Friday.Repository.csproj" />
    <ProjectReference Include="..\..\..\TSI.Friday.Services\src\TSI.Friday.Services\TSI.Friday.Services.csproj" />
  </ItemGroup>
</Project>
